/**
 * Game manifest, put asset filepaths here.
 */
const GameManifest = {
  data: [
    "./assets/sprites/rat.png",
    "./assets/sprites/spikes.png",
    "./assets/sprites/spiketraps.png",
    "./assets/sprites/prototype_background.png",
    "./assets/sprites/StatueCatsMainCharacterWReversed.png",
    "./assets/sprites/Alt_StatueCatsMainCharacterWReversed.png",
    "./assets/sprites/StatueCatsTileset.png",
    "./assets/sprites/platform.png",
    "./assets/sprites/button.png",
    "./assets/sprites/gate.png",
    "./assets/sprites/crate.png",
    "./assets/sprites/effect.png",
    "./assets/sprites/SmokeExplosion.png",
    "./assets/sprites/JumpDust.png",
    "./assets/sprites/ExitEntrance.png",
    "./assets/sprites/Lives.png",
    "./assets/sprites/torch.png",
    "./assets/sprites/YarnBall.png",
    "./assets/sprites/CircleExpand.png",
    "./assets/audio/Victory.wav",
    "./assets/sprites/chalice.png",
    "./assets/sprites/MenuButton.png",
    //"./assets/sprites/MainMenuTemp.png",
    "./assets/sprites/Screen Wipe 640x360-Sheet.png",
    "./assets/audio/Puzzle Game 3.mp3",
    "./assets/audio/synth_beep_02.ogg",
    "./assets/audio/retro_misc_03.ogg",
    "./assets/audio/shot_02.ogg",
    "./assets/audio/synth_misc_08.ogg",
    "./assets/audio/power_up_06.ogg",
    "./assets/audio/synth_misc_01.ogg",
    "./assets/audio/synth_misc_05.ogg",
    "./assets/audio/synth_misc_11.ogg",
    "./assets/audio/retro_explosion_02.ogg",
    "./assets/sprites/menubackground.png",
    "./assets/sprites/title.png",
    "./assets/sprites/navbutton.png",
    "./assets/sprites/LevelSelectButton.png",
    "./assets/sprites/levelicons.png",
  ],
};
